### ISSUE TITLE
Error running the filter

### ISSUE THREAD

**Issue by cechandler** [chdemko/pandoc-codeblock-include#1]
Thank you very much for making this filter. I'm getting an error message that I am not sure how to read and fix it. Any thoughts? Many thanks.

Traceback (most recent call last):
  File "/usr/local/bin/pandoc-codeblock-include", line 9, in <module>
    load_entry_point('pandoc-codeblock-include==0.0.2', 'console_scripts', 'pandoc-codeblock-include')()
  File "/Library/Python/2.7/site-packages/pandoc_codeblock_include.py", line 40, in main
    return run_filter(include, doc = doc)
  File "/Library/Python/2.7/site-packages/panflute/io.py", line 265, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/Library/Python/2.7/site-packages/panflute/io.py", line 252, in run_filters
    dump(doc, output_stream=output_stream)
  File "/Library/Python/2.7/site-packages/panflute/io.py", line 161, in dump
    ensure_ascii=False  # For Pandoc compat
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 210, in encode
    return ''.join(chunks)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3339: ordinal not in range(128)
Error running filter pandoc-codeblock-include:
Filter returned error status 1

**Comment by chdemko** [comment]
Can you please post your files somewhere for testing?
